In [1]:
import numpy as np

In [2]:
# 100 equally spaced numbers between 0 and 5
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [3]:
# generate Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
#generate random numbers from uniform distribution
np.random.rand(5,5)

array([[0.97753779, 0.58822655, 0.22737706, 0.22553818, 0.08478258],
       [0.33837031, 0.31938453, 0.81519415, 0.38240272, 0.81190422],
       [0.29532266, 0.31330502, 0.24070847, 0.99227695, 0.2522795 ],
       [0.51907385, 0.9089686 , 0.44084729, 0.60172245, 0.60627762],
       [0.44290013, 0.27302988, 0.67708159, 0.26724283, 0.38085694]])

In [11]:
#random numbers from normal distribution
np.random.randn(5,5)

array([[ 0.38446596,  0.46873787, -0.68827104, -1.25200848,  0.15349908],
       [ 0.52108307, -0.87429936, -0.9005352 ,  0.02861721,  0.85078952],
       [ 0.67195662, -0.71838209, -0.5173781 , -2.30959877,  0.02485881],
       [ 0.09460702,  1.7582858 , -1.30051314,  0.9244197 ,  0.15237411],
       [-0.26650347, -0.46447005, -0.96981521, -0.69788994,  0.28555064]])

In [10]:
#random integers
np.random.randint(0,100,10)

array([73, 54, 68, 41, 25, 86, 81, 67, 90, 69])

In [14]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [6]:
x1 = np.arange(1,6)
x1 = x1.reshape(5,1)
y1 = np.arange(6,11)
y1 = y1.reshape(1,5)

In [7]:
x1

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [8]:
y1

array([[ 6,  7,  8,  9, 10]])

In [10]:
matrix_mul = np.matmul(x1,y1)

In [13]:
matrix_mul

array([[ 6,  7,  8,  9, 10],
       [12, 14, 16, 18, 20],
       [18, 21, 24, 27, 30],
       [24, 28, 32, 36, 40],
       [30, 35, 40, 45, 50]])

In [14]:
matrix_mul.sum(axis=1)

array([ 40,  80, 120, 160, 200])